version: '3'

networks:
  rabbitmq_network:
    driver: bridge
  mongodb_network:
    driver: bridge
  api_gateway_network:
    driver: bridge
  api_network:
    driver: bridge

services:
  rabbitmq:
    build: ./rabbitmq
    image: claclacla/rabbitmq
    container_name: RabbitMQ
    networks:
      - rabbitmq_network

  mongodb:
    image: mongo:3.4
    container_name: MongoDB
    networks:
      - mongodb_network

  orders-api-server:
    image: claclacla/orders-api-server
    container_name: OrdersAPIServer
    networks:
      - rabbitmq_network
      - mongodb_network
      - api_gateway_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"

  products-api-server:
    image: claclacla/products-api-server
    container_name: ProductsAPIServer
    networks:
      - rabbitmq_network
      - mongodb_network
      - api_gateway_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"

  api-gateway:
    build: ./api-gateway
    image: claclacla/api-gateway
    container_name: APIGateway
    networks:
      - api_gateway_network
      - api_network
    ports:
      - "80:80"
    volumes:
      - "${APP_FOLDER}/docker/dev/api-gateway/conf.d:/etc/nginx/conf.d"

  dev-machine:
    build: ./dev-machine
    image: claclacla/dev-machine
    container_name: DEVMachine
    networks:
      - api_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"