version: '3'

networks:
  rabbitmq_network:
    driver: bridge
  mongodb_network:
    driver: bridge
  api_gateway_network:
    driver: bridge
  api_network:
    driver: bridge

services:
  rabbitmq:
    build: ./rabbitmq
    image: claclacla/rabbitmq
    container_name: RabbitMQ
    networks:
      - rabbitmq_network

  mongodb:
    image: mongo:3.4
    container_name: MongoDB
    networks:
      - mongodb_network

  # Platform events

  platform-events-scheduler:
    build: ./js-microservice
    image: claclacla/js-microservice
    container_name: PlatformEventsScheduler
    environment:
      - MICROSERVICE_PATH=/usr/src/app/microservices/platform-events/scheduler/app.js
    networks:
      - mongodb_network
      - rabbitmq_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"
    links:
      - mongodb
      - rabbitmq
    tty: true
    stdin_open: true

  # Components

  api-server:
    image: claclacla/api-server
    container_name: APIServer
    networks:
      - rabbitmq_network
      - mongodb_network
      - api_gateway_network
    volumes:
      - "${APP_FOLDER}/microservices/api-server:/usr/src/app"
    links:
      - mongodb
      - rabbitmq

  api-gateway:
    build: ./api-gateway
    image: claclacla/api-gateway
    container_name: APIGateway
    networks:
      - api_gateway_network
      - api_network
    ports:
      - "80:80"
    volumes:
      - "${APP_FOLDER}/docker/dev/api-gateway/conf.d:/etc/nginx/conf.d"
    links:
      - api-server

  # Products

  products-socket:
    build: ./js-microservice
    image: claclacla/js-microservice
    container_name: ProductsSocket
    environment:
      - MICROSERVICE_PATH=/usr/src/app/microservices/products/socket/app.js
    networks:
      - mongodb_network
      - rabbitmq_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"
    links:
      - mongodb
      - rabbitmq
    tty: true
    stdin_open: true

  # Dev machine

  dev-machine:
    build: ./dev-machine
    image: claclacla/dev-machine
    container_name: DEVMachine
    networks:
      - api_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"