version: '3'

networks:
  rabbitmq_network:
    driver: bridge
  mongodb_network:
    driver: bridge
  api_network:
    driver: bridge

services:
  rabbitmq:
    build: ./rabbitmq
    image: claclacla/rabbitmq
    container_name: RabbitMQ
    networks:
      - rabbitmq_network
    ports:
      - "5672:5672"

  mongodb:
    image: mongo:3.4
    container_name: MongoDB
    networks:
      - mongodb_network

  order-api-server:
    image: claclacla/order-api-server
    container_name: OrderAPIServer
    networks:
      - rabbitmq_network
      - mongodb_network
      - api_network
    ports:
      - "3000:3000"
    volumes:
      - "${APP_FOLDER}:/usr/src/app"

  dev-machine:
    build: ./dev-machine
    image: claclacla/dev-machine
    container_name: DEVMachine
    networks:
      - api_network
    volumes:
      - "${APP_FOLDER}:/usr/src/app"